<?php

namespace Ebay\Sell\Inventory\Model;

use OpenAPI\Runtime\AbstractModel as AbstractModel;

/**
 * This type is used to identify the charitable organization associated with the
 * listing, and the percentage of the sale proceeds that the charitable
 * organization will receive for each sale generated by the listing. In order to
 * receive a percentage of the sales proceeds, the charitable organization must be
 * registered with the PayPal Giving Fund, which is a partner of eBay for Charity.
 */
class Charity extends AbstractModel
{
    /**
     * The eBay-assigned unique identifier of the charitable organization that will
     * receive a percentage of the sales proceeds. The charitable organization must be
     * reqistered with the PayPal Giving Fund in order to receive sales proceeds
     * through eBay listings. This field is conditionally required if a seller is
     * planning on donating a percentage of the sale proceeds to a charitable
     * organization. The eBay-assigned unique identifier of a charitable organization
     * can be found using the GetCharities call of the Trading API. In the GetCharities
     * call response, this unique identifier is shown in the id attribute of the
     * Charity container.
     *
     * @var string
     */
    public $charityId = null;

    /**
     * This field is the percentage of the purchase price that the charitable
     * organization (identified in the charityId field) will receive for each sale that
     * the listing generates. This field is conditionally required if a seller is
     * planning on donating a percentage of the sale proceeds to a charitable
     * organization. This numeric value can range from 10 to 100, and in any 5
     * (percent) increments in between this range (e.g. 10, 15, 20...95,... 100). The
     * seller would pass in 10 for 10 percent, 15 for 15 percent, 20 for 20 percent,
     * and so on, all the way to 100 for 100 percent.
     *
     * @var string
     */
    public $donationPercentage = null;
}
